version: '3.8'

services:
  oracle-db:
    build:
      context: ./oracle-custom
      dockerfile: Dockerfile
    container_name: oracle_db
    environment:
      ORACLE_PASSWORD: oracle123
      APP_USER: apiuser
      APP_USER_PASSWORD: apipass123
      ORACLE_DATABASE: XEPDB1
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle123@localhost:1521/XEPDB1", "-c", "SELECT 1 FROM dual"]
      interval: 60s
      timeout: 30s
      retries: 3

  flask-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_api
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=oracle+cx_oracle://apiuser:apipass123@oracle-db:1521/XEPDB1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - api-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: api_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./logs:/var/log/frontend
    networks:
      - api-network

volumes:
  oracle_data:

networks:
  api-network:
    driver: bridge